### ISSUE TITLE
Translation labels not working

### ISSUE THREAD

**Issue by Dumcem** [jsfehler/renpy-encyclopaedia#4]
Hi,
when I try to follow the instructions in the encyclopaedia docs (http://renpy-encyclopaedia.readthedocs.io/en/latest/translations.html) to create a translation, I get the following error:

﻿I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 2, in script
    init python:
  File "game/script.rpy", line 9, in <module>
    fr_labels = Labels()
TypeError: __init__() takes exactly 2 arguments (1 given)

This happens even with a very simplified code, based on the example provided in the docs:

    init python:
        # English
        en_encyclopaedia = Encyclopaedia()

        # French
        fr_encyclopaedia = Encyclopaedia()

        fr_labels = Labels()
        fr_labels.sort_alphabetical_label = "De A à Z"

        fr_encyclopaedia.labels = fr_labels

    label start:

        "Not Working"

        return

This happens on Windows 10 Pro, with Ren'Py 7.0.0.196

**Comment by jsfehler** [comment]
This is a typo in the documentation. 

Replace:
`fr_labels = Labels()`
with:
`fr_labels = Labels(fr_encyclopaedia)`

**Comment by Dumcem** [comment]
That worked, thanks!

**Comment by jsfehler** [comment]
Docs updated: 
http://renpy-encyclopaedia.readthedocs.io/en/latest/translations.html
