### ISSUE TITLE
Help with setup?

### ISSUE THREAD

**Issue by Alejo275** [jsfehler/renpy-encyclopaedia#6]
Hello, im attempting to use your framework to contribute with a friend's visual novel
I have been reading your documentation but i dont seem to understand how to make a basic glossary work, i dont that much about programming, but is this that complicated? Can you help me?
In renpy under which file should i start writing the statements for an encyclopaedia object and entries? Where can i ask about this?

**Comment by jsfehler** [comment]
As with the rest of renpy, it doesn't matter which file you use, as long as it's a rpy file.

**Comment by Alejo275** [comment]
Like this?

init python:
    your_new_encyclopaedia = Encyclopaedia()

test = EncEntry(
    parent=your_new_encyclopaedia,
    name="001",
    text=[
        "Test1."
    ],
    viewed_persistent=True,
)

# The game starts here.
label start:

**Comment by jsfehler** [comment]
You're missing indentation

**Comment by jsfehler** [comment]
Also, init python blocks do not go in labels.

**Comment by jsfehler** [comment]
Python code in a label must be in a python block.

**Comment by jsfehler** [comment]
init python blocks cannot be inside a label.
python code in a label must be inside a python block

**Comment by jsfehler** [comment]
ShowMenu takes a string for the name of the screen, ie:

```ShowMenu('encyclopaedia_list', your_new_encyclopaedia) ```

**Comment by Alejo275** [comment]
Its working!!
Thank you so much
