### ISSUE TITLE
Visualization problem with Ren'Py 8.0.3

### ISSUE THREAD

**Issue by Dumcem** [jsfehler/renpy-encyclopaedia#7]
Hi,
I was trying to use the Encyclopedia with Ren'Py 8.0.3, and it seems that the expressions `half_screen_width = config.screen_width` and `half_screen_height = config.screen_height / 2` are giving different results than before (specifically, float values instead of integers). This gives visualization problems that can be avoided changing the code with `half_screen_width = int(config.screen_width / 2)` and `half_screen_height = int(config.screen_height / 2)`.
The reason is, probably, the fact that Python 3.0 always returns a float value as a result for division operations.

Follows the discussion in:
https://github.com/renpy/renpy/issues/4276

**Comment by jsfehler** [comment]
Fixed in version 3.0
